# Probability theory

## Background material

```{theorem, label = "prob-partitions"}
If $P$ is a probability function, then

1. $P\left(A\right)=\sum_{i=1}^{\infty}P\left(A\cap C_{i}\right)$ for any partition $C_{1},C_{2},\ldots$;
2. $P\left(\cup_{i=1}^{\infty}A_{i}\right)\leq\sum_{i=1}^{\infty}P\left(A_{i}\right)$ for any sets $A_{1},A_{2},\ldots$.
```

```{theorem, name = "Bayes' Rule"}
Let $A_{1},A_{2},\ldots$ be a partition of the sample space $\Omega$, and let $B$ be any set. Then, for each $i=1,2,\ldots$,
$$
P\left(A_{i}|B\right)=\frac{P\left(B|A_{i}\right)P\left(A_{i}\right)}{\sum_{j=1}^{\infty}P\left(B|A_{j}\right)P\left(A_{j}\right)}.
$$
```

```{proof}
From the definition of conditional probability, we have
\begin{align*}
P\left(A_{i}|B\right) & =\frac{P\left(A_{i}\cap B\right)}{P\left(B\right)} \\
 & =\frac{P\left(B|A_{i}\right)P\left(A_{i}\right)}{P\left(B\right)}\tag{conditional probability} \\
 & =\frac{P\left(B|A_{i}\right)P\left(A_{i}\right)}{\sum_{j=1}^{\infty}P\left(B\cap A_{j}\right)}\tag{the $A_{j}$ partition $\Omega$} \\
 & =\frac{P\left(B|A_{i}\right)}{\sum_{j=1}^{\infty}P\left(B|A_{j}\right)P\left(A_{j}\right)}.\tag{conditional probability}
\end{align*}
```

```{definition}
The *cumulative distribution function* or *cdf* of a random variable $X$, denoted by $F_{X}\left(x\right)$, is defined by $F_{X}\left(x\right)=P_{X}\left(X\leq x\right)$, for all $x$.
```

```{theorem, label = "properties-of-cdf"}
The function $F\left(x\right)$ is a cdf if and only if the following three conditions hold:

1. $\lim_{x\rightarrow-\infty}F\left(x\right)=0$ and $\lim_{x\rightarrow\infty}F\left(x\right)=1$.
2. $F\left(x\right)$ is a nondecreasing function of $x$.
3. $F\left(x\right)$ is right-continuous; that is, for every number $x_{0}$, $\lim_{x\downarrow x_{0}}F\left(x\right)=F\left(x_{0}\right)$.

(This is Theorem 1.5.3 from @casella2002statistical.)
```

```{proof}
PROOF GOES HERE
```

## Transformations and expectations

### Distributions of functions of a random variable

When transformations are made, it is important to keep track of the sample spaces of the random variables; otherwise, much confusion can arise. When the transformation is from $X$ to $Y=g\left(X\right)$, it is most convenient to use

\begin{equation}
\mathcal{X}=\left\{ x:f_{X}\left(x\right)>0\right\} \quad\text{and}\quad\mathcal{Y}=\left\{ y:y=g\left(x\right)\text{ for some }x\in\mathcal{X}\right\}.
(\#eq:trans-rv-sample-space)
\end{equation}

```{theorem, label = "cdf-of-function-of-rv"}
Let $X$ have cdf $F_{X}\left(x\right)$, let $Y=g\left(X\right)$, and let $\mathcal{X}$ and $\mathcal{Y}$ be defined as in Equation \@ref(eq:trans-rv-sample-space).

1. If $g$ is an increasing function on $\mathcal{X}$, $F_{Y}\left(y\right)=F_{X}\left(g^{-1}\left(y\right)\right)$ for $y\in\mathcal{Y}$.
2. If $g$ is a decreasing function on $\mathcal{X}$ and $X$ is a continuous random variable, $F_{Y}\left(y\right)=1-F_{X}\left(g^{-1}\left(y\right)\right)$ for $y\in\mathcal{Y}$.

(This is Theorem 2.1.3 from @casella2002statistical.)
```

```{proof}
$g$ is a monotone function, i.e., it maps each $x$ to a single $y$, and each $y$ comes from at most one $x$. In this case that $g$ is increasing, we have

\begin{align*}
\left\{ x\in\mathcal{X}:g\left(x\right)\leq y\right\} & =\left\{ x\in\mathcal{X}:g^{-1}\left(g\left(x\right)\right)\leq g^{-1}\left(y\right)\right\} \\
	& =\left\{ x\in\mathcal{X}:x\leq g^{-1}\left(y\right)\right\},
\end{align*}

and the cdf of $Y$ is 

\begin{align*}
F_{Y}\left(y\right)	& =P\left(\left\{ Y\leq y\right\} \right) \\
	& =P\left(\left\{ g\left(X\right)\leq y\right\} \right) \\
	& =P\left(\left\{ x\in\mathcal{X}:g\left(x\right)\leq y\right\} \right) \\
	& =P\left(\left\{ x\in\mathcal{X}:x\leq g^{-1}\left(y\right)\right\} \right) \\
	& =\int_{-\infty}^{g^{-1}\left(y\right)}f_{X}\left(x\right)\dif x \\
	& =F_{X}\left(g^{-1}\left(y\right)\right).
\end{align*}

In the case that $g$ is decreasing, we have

\begin{align*}
\left\{ x\in\mathcal{X}:g\left(x\right)\leq y\right\} & =\left\{ x\in\mathcal{X}:g^{-1}\left(g\left(x\right)\right)\geq g^{-1}\left(y\right)\right\} \\
	& =\left\{ x\in\mathcal{X}:x\geq g^{-1}\left(y\right)\right\},
\end{align*}

and the cdf of $Y$ is

\begin{align*}
F_{Y}\left(y\right)	& =P\left(\left\{ Y\leq y\right\} \right) \\
	& =P\left(\left\{ g\left(X\right)\leq y\right\} \right) \\
	& =P\left(\left\{ x\in\mathcal{X}:g\left(x\right)\leq y\right\} \right) \\
	& =P\left(\left\{ x\in\mathcal{X}:x\geq g^{-1}\left(y\right)\right\} \right) \\
	& =\int_{g^{-1}\left(y\right)}^{\infty}f_{X}\left(x\right)\dif x \\
	& =1-F_{X}\left(g^{-1}\left(y\right)\right).\tag{continuity of $X$}
\end{align*}
```

```{theorem, label = "pdf-of-function-of-rv"}
Let $X$ have pdf $f_{X}\left(x\right)$ and let $Y=g\left(X\right)$, where $g$ is a monotone function. Let $\mathcal{X}=\left\{ x:f_{X}\left(x\right)>0\right\}$  and let $\mathcal{Y}=\left\{ y:y=g\left(x\right),x\in\mathcal{X}\right\}$. Suppose that $f_{X}\left(x\right)$ is continuous on $\mathcal{X}$ and that $g^{-1}\left(y\right)$ has a continuous derivative on $\mathcal{Y}$. Then the pdf of $Y$ is given by

$$
f_{Y}\left(y\right)=
  \begin{cases}
    f_{X}\left(g^{-1}\left(y\right)\right)\left|\dfrac{\dif}{\dif y}g^{-1}\left(y\right)\right|, & y\in\mathcal{Y}\\
    0, & \text{otherwise}
  \end{cases}.
$$

(This is Theorem 2.1.5 from @casella2002statistical.)
```

```{proof}
From Theorem \@ref(thm:cdf-of-function-of-rv) and applying the chain rule, we have

$$
f_{Y}\left(y\right)=
  \dfrac{\dif}{\dif y}F_{Y}\left(y\right)=
  f_{X}\left(g^{-1}\left(y\right)\right)\dfrac{\dif}{\dif y}g^{-1}\left(y\right)
$$

in the case that g is increasing and

$$
f_{Y}\left(y\right)=
  \dfrac{\dif}{\dif y}F_{Y}\left(y\right)=
  0-f_{X}\left(g^{-1}\left(y\right)\right)\dfrac{\dif}{\dif y}g^{-1}\left(y\right)=
  -f_{X}\left(g^{-1}\left(y\right)\right)\dfrac{\dif}{\dif y}g^{-1}\left(y\right)
$$

in the case that $g$ is decreasing, which can be expressed concisely as in the theorem.
```

We will look at $F_{X}^{-1}$, the inverse of the cdf $F_{X}$. If $F_{X}$ is strictly increasing, then $F_{X}^{-1}$ is well defined by

\begin{equation}
F_{X}^{-1}\left(y\right)=x\implies F_{X}\left(x\right)=y.
(\#eq:inverse-cdf-increasing)
\end{equation}

However, if $F_{X}$ is constant on some interval, then $F_{X}^{-1}$ is not well defined by Equation \@ref(eq:inverse-cdf-increasing). Any $x$ satisfying $x_{1}\leq x\leq x_{2}$ satisfies $F_{X}\left(x\right)=y$. This problem is avoided by defining $F_{X}^{-1}\left(y\right)$ for $0<y<1$ by

$$
F_{X}^{-1}\left(y\right)=\inf\left\{ x:F_{X}\left(x\right)\geq y\right\},
$$
a definition that agrees with Equation \@ref(eq:inverse-cdf-increasing) when $F_{X}$ is nonconstant and provides an $F_{X}^{-1}$ that is single-valued even when $F_{X}$ is not strictly increasing. Using this definition, for some interval $\left(x_{1},x_{2}\right)$ on which $F_{X}$ is constant, we have $F_{X}^{-1}\left(y\right)=x_{1}$. At the endpoints of the range of $y$, $F_{X}^{-1}\left(y\right)$ can also be defined. $F_{X}^{-1}\left(1\right)=\infty$ if $F_{X}\left(x\right)<1$ for all $x$ and, for any $F_{X}$, $F_{X}^{-1}\left(0\right)=-\infty$.

```{theorem, name = "Probability integral transformation"}
Let $X$ have continuous cdf $F_{X}\left(x\right)$ and define the random variable $Y$ as $Y=F_{X}\left(X\right)$. Then $Y$ is uniformly distributed on $\left(0,1\right)$, that is, $P\left(\left\{ Y\leq y\right\} \right)=y$, $0<y<1$.

(This is Theorem 2.1.10 from @casella2002statistical; the following proof is given there.)
```

```{proof}
For $Y=F_{X}\left(X\right)$ we have, for $0<y<1$, 

\begin{align*}
P\left(\left\{ Y\leq y\right\} \right) & =P\left(\left\{ F_{X}\left(X\right)\leq y\right\} \right) \\
	& =P\left(\left\{ F_{X}^{-1}\left[F_{X}\left(X\right)\right]\leq F_{X}^{-1}\left(y\right)\right\} \right)\tag{$F_{X}^{-1}$ is increasing} \\
	& =P\left(\left\{ X\leq F_{X}^{-1}\left(y\right)\right\} \right)\tag{see paragraph below} \\
	& =F_{X}\left(F_{X}^{-1}\left(y\right)\right)\tag{definition of $F_{X}$} \\
	& =y.\tag{continuity of $F_{X}$}
\end{align*}

At the endpoints we have $P\left(\left\{ Y\leq y\right\} \right)=1$ for $y\geq 1$ and $P\left(\left\{ Y\leq y\right\} \right)=0$ for $y\leq 0$, showing that $Y$ has a uniform distribution.

The reasoning behind the equality

$$
P\left(\left\{ F_{X}^{-1}\left(F_{X}\left(X\right)\right)\leq F_{X}^{-1}\left(y\right)\right\} \right)=P\left(\left\{ X\leq F_{X}^{-1}\left(y\right)\right\} \right)
$$
  
is somewhat subtle and deserves additional attention. If $F_{X}$ is strictly increasing, then it is true that $F_{X}^{-1}\left(F_{X}\left(x\right)\right)=x$. However, if $F_{X}$ is flat, it may be that $F_{X}^{-1}\left(F_{X}\left(x\right)\right)\neq x$. Suppose $F_{X}$ contains an interval $\left(x_{1},x_{2}\right)$ on which $F_{X}$ is constant, and let $x\in\left[x_{1},x_{2}\right]$. Then $F_{X}^{-1}\left(F_{X}\left(x\right)\right)=x_{1}$ for any $x$ in this interval. Even in this case, though, the probability equality holds, since $P\left(\left\{ X\leq x\right\} \right)=P\left(\left\{ X\leq x_{1}\right\} \right)$ for any $x\in\left[x_{1},x_{2}\right]$. The flat cdf denotes a region of $0$ probability $(P\left(\left\{ x_{1}<X\leq x\right\} \right)=F_{X}\left(x\right)-F_{X}\left(x_{1}\right)=0)$.
```

### Expected values

```{theorem, label = "properties-of-expectation"}
Let $X$ be a random variable and let $a$, $b$, and $c$ be constants. Then for any functions $g_{1}\left(x\right)$ and $g_{2}\left(x\right)$ whose expectations exist,

1. $\E\left[ag_{1}\left(X\right)+bg_{2}\left(X\right)+c\right]=a\E\left[g_{1}\left(X\right)\right]+b\E\left[g_{2}\left(X\right)\right]+c$.
2. If $g_{1}\left(x\right)\geq 0$ for all $x$, then $\E\left[g_{1}\left(X\right)\right]\geq 0$.
3. If $g_{1}\left(x\right)\geq g_{2}\left(x\right)$ for all $x$, then $\E\left[g_{1}\left(X\right)\right]\geq\E\left[g_{2}\left(X\right)\right]$.
4. If $a\leq g_{1}\left(x\right)\leq b$ for all $x$, then $a\leq\E\left[g_{1}\left(X\right)\right]\leq b$.

(This is Theorem 2.2.5 from @casella2002statistical; the following proof is given there.)
```

```{proof}
PROOF GOES HERE
```

### Moments and moment generating functions

```{definition}
For each integer $n$, the $n\text{th}$ *moment* of $X$ or $(F_{X}\left(x\right))$, $\mu'_{n}$, is

$$
\mu'_{n}=\E\left[X^{n}\right].
$$

The $n\text{th}$ *central moment* of $X$, $\mu_{n}$, is

$$
\mu_{n}=\E\left[\left(X-\mu\right)^{n}\right],
$$

where $\mu=\mu'_{1}=\E\left[X\right]$.
```

```{definition}
Let $X$ be a random variable with cdf $F_{X}$. The *moment generating function* (mgf) of $X$ (or $F_{X}$), denoted by $M_{X}\left(t\right)$, is

$$
M_{X}\left(t\right)=\E\left[\mathrm{e}^{tX}\right],
$$

provided that the expectation exists for $t$ in some neighborhood of $0$. That is, there is an $h>0$ such that, for all $t$ in $-h<t<h$, $\E\left[\mathrm{e}^{tX}\right]$ exists. If the expectation does not exist in a neighborhood of $0$, we say that the moment generating function does not exist.
```

More explicitly, we can write the mgf of $X$ as

$$
M_{X}\left(t\right)=\int_{-\infty}^{\infty}\mathrm{e}^{tx}f_{X}\left(x\right)\dif x
$$
if $X$ is continuous, or

$$
M_{X}\left(t\right)=\sum_{x}\mathrm{e}^{tx}P\left(\left\{ X=x\right\} \right)
$$

if $X$ is discrete.

```{theorem}
If $X$ has mgf $M_{X}\left(t\right)$, then

$$
\E\left[X^{n}\right]=M_{X}^{\left(n\right)}\left(0\right),
$$

where we define

$$
M_{X}^{\left(n\right)}\left(0\right)=\frac{\dif^{n}}{\dif t^{n}}M_{X}\left(t\right)\Bigr\vert_{t=0}.
$$
  
That is, the $n\text{th}$ moment is equal to the $n\text{th}$ derivative of $M_{X}\left(t\right)$ evaluated at $t=0$. 

(This is Theorem 2.3.7 from @casella2002statistical; the following proof is given there.)
```

```{proof}
Assuming that we can differentiate under the integral sign, we have

\begin{align*}
\frac{\dif}{\dif t}M_{X}\left(t\right) & =\frac{\dif}{\dif t}\int_{-\infty}^{\infty}\mathrm{e}^{tx}f_{X}\left(x\right)\dif x \\
  & =\int_{-\infty}^{\infty}\left(\frac{\dif}{\dif t}\mathrm{e}^{tx}\right)f_{X}\left(x\right)\dif x \\
  & =\int_{-\infty}^{\infty}\left(x\mathrm{e}^{tx}\right)f_{X}\left(x\right)\dif x \\
  & =\E\left[X\mathrm{e}^{tX}\right].
\end{align*}

Thus,

$$
\frac{\dif}{\dif t}M_{X}\left(t\right)\Bigr\vert_{t=0}=\E\left[X\mathrm{e}^{tX}\right]\Big\vert_{t=0}=\E\left[X\mathrm{e}^{0}\right]=\E\left[X\right].
$$
  
Noting that

$$
\frac{\dif^{n}}{\dif t^{n}}\mathrm{e}^{tx}=\frac{\dif^{n-1}}{\dif t^{n-1}}\left[\frac{\dif}{\dif t}\mathrm{e}^{tx}\right]=\frac{\dif^{n-2}}{\dif t^{n-2}}\left[\frac{\dif}{\dif t}x\mathrm{e}^{tx}\right]=\frac{\dif^{n-2}}{\dif t^{n-2}}x^{2}\mathrm{e}^{tx}=\frac{\dif}{\dif t}x^{n-1}\mathrm{e}^{tx}=x^{n}\mathrm{e}^{tx},
$$
  
we can establish that

\begin{align*}
\frac{\dif^{n}}{\dif t^{n}}M_{X}\left(t\right)\Bigr\vert_{t=0} & =\frac{\dif^{n}}{\dif t^{n}}\int_{-\infty}^{\infty}\mathrm{e}^{tx}f_{X}\left(x\right)\dif x\Big\vert_{t=0} \\
	& =\int_{-\infty}^{\infty}\left(\frac{\dif^{n}}{\dif t^{n}}\mathrm{e}^{tx}\right)f_{X}\left(x\right)\dif x\Big\vert_{t=0} \\
	& =\int_{-\infty}^{\infty}\left(x^{n}\mathrm{e}^{tx}\right)f_{X}\left(x\right)\dif x\Big\vert_{t=0} \\
	& =\E\left[X^{n}\mathrm{e}^{tX}\right]\Big\vert_{t=0} \\
	& =\E\left[X^{n}\right].
\end{align*}
```

```{lemma, label = "limit-sequence-exponential"}
Let $a_{1},a_{2},\ldots$ be a sequence of numbers converging to $a$, that is, $\lim_{n\rightarrow\infty}a_{n}=a$. Then

$$
\lim_{n\rightarrow\infty}\left(1+\frac{a_{n}}{n}\right)^{n}=\mathrm{e}^{a}.
$$
  
(This is Lemma 2.3.14 from @casella2002statistical.)
```

```{theorem, label = "mgf-affine-transform"}
For any constants $a$ and $b$, the mgf of the random variable $aX+b$ is given by

$$
M_{aX+b}\left(t\right)=\mathrm{e}^{bt}M_{X}\left(at\right).
$$
  
(This is Theorem 2.3.15 from @casella2002statistical.; the following proof is given there.)
```

```{proof}
By definition,

$$
M_{aX+b}\left(t\right)=
  \E\left[\mathrm{e}^{\left(aX+b\right)t}\right]=
  \E\left[\mathrm{e}^{\left(aX\right)t}\mathrm{e}^{bt}\right]=
  \mathrm{e}^{bt}\E\left[\mathrm{e}^{\left(at\right)X}\right]=
  \mathrm{e}^{bt}M_{X}\left(at\right),
$$
  
proving the theorem.
```

## Multiple random variables

### Conditional distributions and independence

```{definition}
Let $\left(X,Y\right)$ be a bivariate random vector with joint pdf or pmf $f\left(x,y\right)$ and marginal pdfs or pmfs $f_{X}\left(x\right)$ and $f_{Y}\left(y\right)$. Then $X$ and $Y$ are called *independent random variables* if, for every $x\in\mathbb{R}$ and $y\in\mathbb{R}$, $f\left(x,y\right)=f_{X}\left(x\right)f_{Y}\left(y\right)$.
```

```{theorem, label = "expected-value-of-two-ind-rvs"}
Let $X$ and $Y$ be independent random variables.

1. For any $\mathcal{A}\subset\mathbb{R}$ and $\mathcal{B}\subset\mathbb{R}$, $P\left(\left\{ X\in \mathcal{A}\right\} \cap\left\{ Y\in \mathcal{B}\right\} \right)=P\left(\left\{ X\in \mathcal{A}\right\} \right)P\left(\left\{ Y\in \mathcal{B}\right\} \right)$; that is, the events $\left\{ X\in \mathcal{A}\right\}$  and $\left\{ Y\in \mathcal{B}\right\}$ are independent events.
2. Let $g\left(x\right)$ be a function only of $x$ and $h\left(y\right)$ be a function only of $y$. Then

$$
\E\left[g\left(X\right)h\left(Y\right)\right]=\E\left[g\left(X\right)\right]\E\left[h\left(Y\right)\right].
$$

(This is Theorem 4.2.10 from @casella2002statistical; the following proof is given there.)
```

```{proof}
For continuous random variables, part (2) is proved by noting that

\begin{align*}
\E\left[g\left(X\right)h\left(Y\right)\right] & =\int_{-\infty}^{\infty}\int_{-\infty}^{\infty}g\left(x\right)h\left(y\right)f\left(x,y\right)\dif x\dif y \\
	& =\int_{-\infty}^{\infty}\int_{-\infty}^{\infty}g\left(x\right)h\left(y\right)f_{X}\left(x\right)f_{Y}\left(y\right)\dif x\dif y\tag{independence} \\
	& =\int_{-\infty}^{\infty}h\left(y\right)f_{Y}\left(y\right)\int_{-\infty}^{\infty}g\left(x\right)f_{X}\left(x\right)\dif x\dif y \\
	& =\left(\int_{-\infty}^{\infty}g\left(x\right)f_{X}\left(x\right)\dif x\right)\left(\int_{-\infty}^{\infty}h\left(y\right)f_{Y}\left(y\right)\dif y\right) \\
	& =\E\left[g\left(X\right)\right]\E\left[h\left(Y\right)\right].
\end{align*}
  
The result for discrete random variables is proved by replacing integrals by sums. Part (1) can be proved by series of steps similar to those above or by the following argument. Let $g\left(x\right)$ be the indicator function of the set $\mathcal{A}$. Let $h\left(y\right)$ be the indicator function of the set $\mathcal{B}$. Note that $g\left(x\right)h\left(y\right)$ is the indicator function of the set $\mathcal{C}\subset\mathbb{R}^{2}$ defined by $\mathcal{C}=\left\{ \left(x,y\right):x\in \mathcal{A},y\in \mathcal{B}\right\}$. Thus using the expectation equality just proved, we have

\begin{align*}
P\left(\left\{ X\in A\right\} \cap\left\{ Y\in B\right\} \right) & =P\left(\left\{ \left(X,Y\right)\in C\right\} \right) \\
	& =\E\left[g\left(X\right)h\left(Y\right)\right] \\
	& =\E\left[g\left(X\right)\right]\E\left[h\left(Y\right)\right] \\
	& =P\left(\left\{ X\in A\right\} \right)P\left(\left\{ Y\in B\right\} \right).
\end{align*}
```

```{theorem, label = "mgf-of-sum-of-two-ind-rvs"}
Let $X$ and $Y$ be independent random variables with moment generating functions $M_{X}\left(t\right)$ and $M_{Y}\left(t\right)$. Then the moment generating function of the random variable $Z=X+Y$ is given by $M_{Z}\left(t\right)=M_{X}\left(t\right)M_{Y}\left(t\right)$.

(This is Theorem 4.2.12 from @casella2002statistical; the following proof is given there.)
```

```{proof}
Using the definition of the mgf and Theorem \@ref(thm:expected-value-of-two-ind-rvs), we have

$$
M_{Z}\left(t\right)=
  \E\left[\mathrm{e}^{tZ}\right]=
  \E\left[\mathrm{e}^{t\left(X+Y\right)}\right]=
  \E\left[\mathrm{e}^{tX}\mathrm{e}^{tY}\right]=
  \E\left[\mathrm{e}^{tX}\right]\E\left[\mathrm{e}^{tY}\right]=
  M_{X}\left(t\right)M_{Y}\left(t\right).
$$
```

### Covariance and correlation

```{definition}
The *covariance* of $X$ and $Y$ is the number defined by

$$
\Cov\left(X,Y\right)=\E\left[\left(X-\mu_{X}\right)\left(Y-\mu_{Y}\right)\right].
$$
```

```{definition}
The *correlation* of $X$ and $Y$ is the number defined by

$$
\rho_{XY}=\frac{\Cov\left(X,Y\right)}{\sigma_{X}\sigma_{Y}}.
$$

The value $\rho_{XY}$ is also called the *correlation coefficient*.
```
