--- 
title: "A Master's Companion"
author: "Sean Wilson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Notes and supporting material for selected courses from Georgetown's Master of Science in Mathematics and Statistics program"
---

# Introduction

This is a compilation of course notes, worked examples, and other supporting materials for selected courses from Georgetown's Master of Science in Mathematics and Statistics program. The courses currently covered include

- MATH-502 Deterministic Mathematical Models
- MATH-503 Mathematical Statistics
- MATH-504 Numerical Methods (*in progress*)
- MATH-640 Bayesian Statistics (*in progress*)

Additional planned courses include

- MATH-611 Stochastic Simulation
- MATH-623 Sparse Representations and Random Sampling
- MATH-658 Survey Sampling

## Prerequisites

We assume knowledge of multivariable calculus and linear algebra, as well as a first course in probability. We introduce, but do not dwell on, a number of results from analysis and probability that are required for the material that follows.
